# Definition of QA pipeline at SonarSource
#
# Possible values for SLAVE: "linux" (for linux machines connected to DB services)

TEST:
  - plugin
  - ruling
  - semantic

SQ_VERSION:
  - LTS
  - DEV
  - LATEST_RELEASE

exclude:
#exclude plugin tests on windows slaves
  - TEST: plugin
    SLAVE: windows
    SQ_VERSION: LTS
  - TEST: plugin
    SLAVE: windows
    SQ_VERSION: DEV
  - TEST: plugin
    SLAVE: windows
    SQ_VERSION: LATEST_RELEASE
#exclude all ruling jobs other than on LATEST_RELEASE on linux
  - TEST: ruling
    SLAVE: linux
    SQ_VERSION: LTS
  - TEST: ruling
    SLAVE: linux
    SQ_VERSION: DEV
#exclude all ruling jobs other than on LATEST_RELEASE on windows
  - TEST: ruling
    SLAVE: windows
    SQ_VERSION: LTS
  - TEST: ruling
    SLAVE: windows
    SQ_VERSION: DEV
#eclude all semantic jobs on linux slaves other than LATEST_RELEASE
  - TEST: semantic
    SLAVE: linux
    SQ_VERSION: LTS
  - TEST: semantic
    SLAVE: linux
    SQ_VERSION: DEV
#eclude all semantic jobs on windows slaves
  - TEST: semantic
    SLAVE: windows
    SQ_VERSION: LTS
  - TEST: semantic
    SLAVE: windows
    SQ_VERSION: DEV
  - TEST: semantic
    SLAVE: windows
    SQ_VERSION: LATEST_RELEASE
